server.port=${PORT:8666}
logging.level.org.atmosphere = warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,org.meisl.showcase

public.key=BIr6jQNZ-grcbfrM_-tNVkCOocFV25h0Z7pHhh8KoGPnXpoB3TrpehIsZaxaC-fpE4I9yAUTQTJoCtyDm3obi4U
private.key=lp3otjzAcYH0OPvv3mq4ZloigHc00DHg2CCdLP9zH-A

subject=Test Notifi